// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2IUcsdvC5V0ZnSb99czMRcFsaDIjwlhA',
    appId: '1:587640969766:web:636501198faa67c56564e7',
    messagingSenderId: '587640969766',
    projectId: 'melon-ticket-mvp-2026',
    authDomain: 'melon-ticket-mvp-2026.firebaseapp.com',
    storageBucket: 'melon-ticket-mvp-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0lSwPtlWJNFAreEKCdfqHx07b-_Yl7po',
    appId: '1:587640969766:android:07c0f1dc931a89776564e7',
    messagingSenderId: '587640969766',
    projectId: 'melon-ticket-mvp-2026',
    storageBucket: 'melon-ticket-mvp-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbJkdTpPvJb8wpcPOzIvijid2vx8WWvDQ',
    appId: '1:587640969766:ios:dd870e36924800fa6564e7',
    messagingSenderId: '587640969766',
    projectId: 'melon-ticket-mvp-2026',
    storageBucket: 'melon-ticket-mvp-2026.firebasestorage.app',
    iosBundleId: 'com.example.melonTicketApp',
  );
}
